# Site settings
title: "ENUM Mandori"
email: "mandori970603@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mandori.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: "Mandorica"

# Build settings
markdown: kramdown

remote_theme : mmistakes/minimal-mistakes